site_name: Caleb Burnham — MEGR 2157 Portfolio
theme:
  name: material
  features:
    - navigation.sections
    - toc.integrate

nav:
  - Home: index.md
  - Assignments:
      - Assignment 1: a1.md
      - Assignment 2: a2.md
